kind: Deployment
apiVersion: apps/v1
metadata:
  name: scylla-operator
  namespace: scylla-operator
  
  labels:
    app.kubernetes.io/instance: scylla-operator
    app.kubernetes.io/name: scylla-operator
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: scylla-operator
    meta.helm.sh/release-namespace: scylla-operator
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: scylla-operator
      app.kubernetes.io/name: scylla-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: scylla-operator
        app.kubernetes.io/name: scylla-operator
    spec:
      containers:
        - name: scylla-operator
          image: scylladb/scylla-operator:1.7.3
          args:
            - operator
            - '--loglevel=2'
          env:
            - name: SCYLLA_OPERATOR_IMAGE
              value: scylladb/scylla-operator:1.7.3
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 32Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsPolicy: ClusterFirst
      serviceAccountName: scylla-operator
      serviceAccount: scylla-operator
      securityContext: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: scylla-operator
                    app.kubernetes.io/name: scylla-operator
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 2
  updatedReplicas: 2
  readyReplicas: 2
  availableReplicas: 2
  