# Specify desired Scylla Operator image
image:
  repository: scylladb
  pullPolicy: IfNotPresent
  tag: ""

# Resources allocated to Scylla Operator pods
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 32Mi

webhook:
  createSelfSignedCertificate: true
  certificateSecretName: ""
