kind: Deployment
apiVersion: apps/v1
metadata:
  name: webhook-server
  namespace: scylla-operator
  
  labels:
    app.kubernetes.io/instance: webhook-server
    
    app.kubernetes.io/name: webhook-server
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: scylla-operator
    meta.helm.sh/release-namespace: scylla-operator
  
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: webhook-server
      app.kubernetes.io/name: webhook-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: webhook-server
        app.kubernetes.io/name: webhook-server
    spec:
      volumes:
        - name: cert
          secret:
            secretName: scylla-operator-serving-cert
            defaultMode: 420
      containers:
        - name: webhook-server
          image: scylladb/scylla-operator:1.7.3
          args:
            - run-webhook-server
            - '--loglevel=2'
            - '--tls-cert-file=/tmp/serving-certs/tls.crt'
            - '--tls-private-key-file=/tmp/serving-certs/tls.key'
          ports:
            - name: webhook-server
              containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - name: cert
              readOnly: true
              mountPath: /tmp/serving-certs
          livenessProbe:
            httpGet:
              path: /readyz
              port: 5000
              scheme: HTTPS
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
              scheme: HTTPS
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/bin/sleep
                  - 15s
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      serviceAccountName: webhook-server
      serviceAccount: webhook-server
      securityContext: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: webhook-server
                    app.kubernetes.io/name: webhook-server
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 2
  updatedReplicas: 2
  readyReplicas: 2
  availableReplicas: 2
  