# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: "5e5513e5-e67e-4f23-9035-45d04b3de574"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: talentappvault
    cloudName: "AzurePublicCloud"                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: flaskAppSecret
          objectType: secret        # object types: secret, key, or cert
          objectAlias: flaskAppSecret
          # objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: flaskAppToken
          objectType: secret        # object types: secret, key, or cert
          objectAlias: flaskAppToken
        - |
          objectName: startIncidentUsername
          objectType: secret        # object types: secret, key, or cert
          objectAlias: startIncidentUsername
        - |
          objectName: startIncidentPassword
          objectType: secret        # object types: secret, key, or cert
          objectAlias: startIncidentPassword
        - |
          objectName: snipApiKey
          objectType: secret        # object types: secret, key, or cert
          objectAlias: snipApiKey
        - |
          objectName: scyllaCertChain
          objectType: secret        # object types: secret, key, or cert
          objectAlias: scyllaCertChain
        - |
          objectName: scylladbUsername
          objectType: secret        # object types: secret, key, or cert
          objectAlias: scylladbUsername
        - |
          objectName: scylladbPassword
          objectType: secret        # object types: secret, key, or cert
          objectAlias: scylladbPassword
        - |
          objectName: saeApiKey
          objectType: secret        # object types: secret, key, or cert
          objectAlias: saeApiKey
        - |
          objectName: tmsStartIncidentKey
          objectType: secret        # object types: secret, key, or cert
          objectAlias: tmsStartIncidentKey
        - |
          objectName: pagerDutyIntegrationKey
          objectType: secret        # object types: secret, key, or cert
          objectAlias: pagerDutyIntegrationKey
        - |
          objectName: incidentManagerSecret
          objectType: secret        # object types: secret, key, or cert
          objectAlias: incidentManagerSecret
        - |
          objectName: slackClientSecret
          objectType: secret        # object types: secret, key, or cert
          objectAlias: slackClientSecret
        - |
          objectName: slackSigningSecret
          objectType: secret        # object types: secret, key, or cert
          objectAlias: slackSigningSecret
        - |
          objectName: slackBotAccessToken
          objectType: secret        # object types: secret, key, or cert
          objectAlias: slackBotAccessToken
        # - |
        #   objectName: pagerDutyIntegrationKey
        #   objectType: secret        # object types: secret, key, or cert
        #   objectAlias: pagerDutyIntegrationKey
    tenantId: d420b80d-bc1a-429d-b6c6-587896c20153          # The tenant ID of the key vault
  secretObjects:
    - data:
        - key: flaskAppSecret
          objectName: FLASK_APP_SECRET
        - key: flaskAppToken
          objectName: FLASK_APP_TOKEN
        - key: startIncidentUsername
          objectName: API_USERNAME
        - key: startIncidentPassword
          objectName: API_PASSWORD
        - key: snipApiKey
          objectName: SNIP_API_KEY
        - key: scyllaCertChain
          objectName: INTERNAL_CA_TRUSTCHAIN_CERT_PEM
        - key: scylladbUsername
          objectName: CASSANDRA_APP_USER
        - key: scylladbPassword
          objectName: CASSANDRA_APP_PW
        - key: saeApiKey
          objectName: SAE_API_CREDS
        - key: tmsStartIncidentKey
          objectName: TMS_API_CREDS
        - key: pagerDutyIntegrationKey
          objectName: PAGERDUTY_INTEGRATION_KEY
        - key: incidentManagerSecret
          objectName: INCIDENT_MANAGER_SECRET
        - key: slackClientSecret
          objectName: SLACK_CLIENT_SECRET
        - key: slackSigningSecret
          objectName: SLACK_SIGNING_SECRET
        - key: slackBotAccessToken
          objectName: SLACK_OAUTH_ACCESS_TOKEN
        - key: slackBotAccessToken
          objectName: SLACK_BOT_USER_ACCESS_TOKEN
      secretName: noc-bot
      type: Opaque