kind: Service
apiVersion: v1
metadata:
  name: concierge-bot
  namespace: im
  
  labels:
    name: concierge-bot
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    name: concierge-bot
  type: ClusterIP
status:
  loadBalancer: {}