kind: ConfigMap
apiVersion: v1
metadata:
  name: scylla-config
  namespace: im
  
data:
  scylla.yaml: |
    authenticator: PasswordAuthenticator
    authorizer: CassandraAuthorizer
    client_encryption_options:
        enabled: true
        certificate: /etc/scylla-certs/scylla-im.cert.pem
        keyfile: /etc/scylla-certs/scylla-im.key.pem
    cluster_name: "im-scylla"
    internode_compression: dc
    server_encryption_options:
        internode_encryption: all
        certificate: /etc/scylla-certs/scylla-im.cert.pem
        keyfile: /etc/scylla-certs/scylla-im.key.pem
        truststore: /etc/intermediate-ca/ca-chain.cert.pem
        require_client_auth: true
    write_request_timeout_in_ms: 30000
